import {
  BarChart3,
  Bot,
  Boxes,
  Building2,
  Cloud,
  CreditCard,
  FileStack,
  FileText,
  FolderKanban,
  KeyRound,
  LifeBuoy,
  ListChecks,
  Server,
  Settings,
  ShieldCheck,
  TrendingUp,
  UserCog,
  Workflow,
} from 'lucide-react'
import { PERMISSIONS } from './roles'

// Fuente única de los módulos del sistema. Cada módulo declara los permisos
// que habilitan su ruta y su aparición en la navegación.
// Los módulos de negocio aún NO se desarrollan; se montan como placeholders.
export const MODULES = [
  {
    path: '/clientes',
    label: 'Clientes',
    description: 'Administra la cartera de clientes del ecosistema.',
    icon: Building2,
    section: 'Operación',
    permissions: [PERMISSIONS.CLIENTS_VIEW, PERMISSIONS.CLIENTS_VIEW_ASSIGNED],
  },
  {
    path: '/leads',
    label: 'Leads',
    description: 'Solicitudes y prospectos provenientes de la landing.',
    icon: TrendingUp,
    section: 'Operación',
    permissions: [PERMISSIONS.LEADS_VIEW],
  },
  {
    path: '/cotizaciones',
    label: 'Cotizaciones',
    description: 'Propuestas económicas y líneas de cotización.',
    icon: FileText,
    section: 'Operación',
    permissions: [PERMISSIONS.QUOTES_VIEW],
  },
  {
    path: '/proyectos',
    label: 'Proyectos',
    description: 'Seguimiento de proyectos, entregas y estados.',
    icon: FolderKanban,
    section: 'Operación',
    permissions: [
      PERMISSIONS.PROJECTS_VIEW,
      PERMISSIONS.PROJECTS_VIEW_ASSIGNED,
      PERMISSIONS.PROJECTS_VIEW_OWN,
    ],
  },
  {
    path: '/tareas',
    label: 'Tareas',
    description: 'Tareas y avances de los proyectos.',
    icon: ListChecks,
    section: 'Operación',
    permissions: [PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_UPDATE_ASSIGNED],
  },
  {
    path: '/servicios',
    label: 'Servicios',
    description: 'Catálogo de servicios y servicios contratados.',
    icon: Boxes,
    section: 'Operación',
    permissions: [PERMISSIONS.SERVICES_VIEW, PERMISSIONS.SERVICES_VIEW_OWN],
  },
  {
    path: '/pagos',
    label: 'Pagos',
    description: 'Pagos, comprobantes y validaciones.',
    icon: CreditCard,
    section: 'Operación',
    permissions: [PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_VIEW_OWN],
  },
  {
    path: '/documentos',
    label: 'Documentos',
    description: 'Contratos, facturas, informes y entregables.',
    icon: FileStack,
    section: 'Operación',
    permissions: [PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_VIEW_OWN],
  },
  {
    path: '/soporte',
    label: 'Soporte',
    description: 'Solicitudes de soporte y atención al cliente.',
    icon: LifeBuoy,
    section: 'Operación',
    permissions: [
      PERMISSIONS.SUPPORT_VIEW,
      PERMISSIONS.SUPPORT_VIEW_ASSIGNED,
      PERMISSIONS.SUPPORT_VIEW_OWN,
    ],
  },
  {
    path: '/usuarios',
    label: 'Usuarios',
    description: 'Usuarios internos del sistema.',
    icon: UserCog,
    section: 'Gestión',
    permissions: [PERMISSIONS.USERS_VIEW],
  },
  {
    path: '/roles',
    label: 'Roles y permisos',
    description: 'Cargos y permisos del sistema (RBAC/ACL).',
    icon: KeyRound,
    section: 'Gestión',
    permissions: [PERMISSIONS.ROLES_VIEW],
  },
  {
    path: '/reportes',
    label: 'Reportes',
    description: 'Reportes y métricas de la operación.',
    icon: BarChart3,
    section: 'Gestión',
    permissions: [PERMISSIONS.REPORTS_VIEW],
  },
  {
    path: '/configuracion',
    label: 'Configuración',
    description: 'Configuración global del ecosistema.',
    icon: Settings,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.SETTINGS_VIEW],
  },
  {
    path: '/seguridad',
    label: 'Seguridad',
    description: 'Seguridad global y control de acceso.',
    icon: ShieldCheck,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.SECURITY_MANAGE],
  },
  {
    path: '/infraestructura',
    label: 'Infraestructura',
    description: 'Infraestructura de los proyectos del ecosistema.',
    icon: Server,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.INFRASTRUCTURE_VIEW],
  },
  {
    path: '/automatizaciones',
    label: 'Automatizaciones',
    description: 'THALEX Automations — automatización de procesos.',
    icon: Workflow,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.AUTOMATIONS_VIEW],
  },
  {
    path: '/ia',
    label: 'THALEX IA',
    description: 'Soluciones de inteligencia artificial.',
    icon: Bot,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.AI_VIEW],
  },
  {
    path: '/hosting',
    label: 'THALEX Hosting',
    description: 'Infraestructura tecnológica administrada.',
    icon: Cloud,
    section: 'Ecosistema',
    permissions: [PERMISSIONS.HOSTING_VIEW],
  },
]

export function getModuleByPath(path) {
  return MODULES.find((m) => m.path === path)
}
